### ISSUE TITLE
Error with Get-FalconIncident -Detailed

### ISSUE THREAD

**Issue by Factorization** [CrowdStrike/psfalcon#11]
It looks like there is an issue with `Get-FalconIncident -Detailed`. The validation is looking for a GUID, but the IDs for incidents aren't a GUID. 

![image](https://user-images.githubusercontent.com/10674846/105416009-5f0d8e00-5bee-11eb-8b13-541041e8a0e6.png)

**Comment by bk-cs** [comment]
- Did you run any commands before running Get-FalconIncident?
- I made a couple additional changes that slightly changed the "parameters lookup" code. Could you remove/reinstall and try to recreate this?

When I look, it's always showing the right "inc:\w{32}:\w{32}" pattern.

**Comment by Factorization** [comment]
Yeah I ran `Get-FalconQueue` before this command. I re-cloned the repo and re-ran the commands. Now `Get-FalconIncident` works, but `Get-FalconQueue` does not. I get an error that it can't validate parameter Ids. It looks like it is looking for a pattern `inc:\w{32}:\w{32}`, but the Ids for the sessions are GUIDs.

**Comment by bk-cs** [comment]
Yeah, that's correct. I've got a file (`Data/Patterns.psd1`) that matches to the URL of the endpoint you're accessing to determine the RegEx for inputting `id` or `ids` fields. It sounds like that's not "disposing" properly, kind of like the other parameters before. I didn't modify how the "patterns" are done when I made those other changes, so I might need to tune that one up a bit. 

I'll see if I can follow some of the same logic that I did for the other parameter properties and sort it out. Thanks!

**Comment by bk-cs** [comment]
Ok, I just made a change to ensure that the patterns aren't being overwritten as new endpoints are looked up. I tested as many commands as I could think of and couldn't reproduce the issue again. Please try reinstalling and let me know if the issue persists.

Thanks again for the help, you've been critical in helping iron out these bugs as I prepare to get the module signed and on the PowerShell Gallery!

**Comment by Factorization** [comment]
It looks like that fixed the issue. Thanks!
