### ISSUE TITLE
[ BUG ] Get-FalconVulnerability - "Cannot validate argument on parameter 'Filter'" error when passing timestamps containing colons in the updated_timestamp field

### ISSUE THREAD

**Issue by guy-user** [CrowdStrike/psfalcon#144]
**Describe the bug**
If you use timestamps containing colons in the updated_timestamp field the PSFalcon module throws the error listed in the title.

If you reduce the timestamp down so that it does not include colons the command works fine.

Example
CMD: Get-FalconVulnerability -Filter "updated_timestamp:<'2021-07-12T07:35:07'" -Detailed -All
RESULT: Get-FalconVulnerability : Cannot validate argument on parameter 'Filter'. 'updated_timestamp:<'2021-07-12T07:35:07'' is not a valid Falcon Query Language statement.

CMD: Get-FalconVulnerability -Filter "updated_timestamp:<'2021-07-12T07'" -Detailed -All
RESULT: Vuln data is returned as expected

In version <=2.1.4 this error does not occur.

In version 2.1.5 including any colon in the timestamp will cause the module to throw an error, as above.

In version 2.1.6 it is only when you include a second colon that an error occurs. 
So this works fine
Get-FalconVulnerability -Filter "updated_timestamp:<'2021-07-12T07:35'" -Detailed -All
But this throws an error
Get-FalconVulnerability -Filter "updated_timestamp:<'2021-07-12T07:35:07'" -Detailed -All

**To Reproduce**
See above

**Expected behavior**
I expect valid vuln data to be returned when using full timestamps.

**Environment (please complete the following information):**
 - OS: Windows Server 2016 v1607
OS Version: 10.0.14393 N/A Build 14393

 - PowerShell:
Major  Minor  Build  Revision
5      1      14393  4583    

 - PSFalcon: 2.1.5

**Additional context**

**Comment by bk-cs** [comment]
I believe this is related to the overly restrictive RegEx being used by a new function called `Test-FqlStatement`. 

Can you try the changes listed at the end of [issue 138](https://github.com/CrowdStrike/psfalcon/issues/138)?

**Comment by guy-user** [comment]
Hi bk-cs, 

Unfortunately the current master branch code still sufferers the same error as the master version available at the time I posted the bug.

In release version 2.1.5 including any colon in the timestamp will cause the module to throw an error.

In version 2.1.6 it is only when you include a second colon that an error occurs.

So for v2.1.6

This works
Get-FalconVulnerability -Filter "updated_timestamp:>'2021-11-17T09:09'" -All -Detailed

But This throws an error
Get-FalconVulnerability -Filter "updated_timestamp:>'2021-11-17T09:09:09'" -All -Detailed

Cheers

**Comment by bk-cs** [comment]
Thank you! I've updated the module to accept the additional semicolon. Please follow these steps to update your local module accordingly:

* Replace your local `Private\Private.ps1` file with the contents of this version: https://raw.githubusercontent.com/CrowdStrike/psfalcon/master/Private/Private.ps1
* Open a new PowerShell session
* Re-import your modified version of v2.1.5 with `Import-Module -Name PSFalcon -RequiredVersion 2.1.5`

**Comment by bk-cs** [comment]
Resolved with v2.1.6 release.

**Comment by guy-user** [comment]
Thanks bk-cs, I can confirm the issue has been fixed in the 2.1.6 release 👍
