### ISSUE TITLE
[ BUG ] Get-FalconHost -Include zero_trust_assessment not attaching properly

### ISSUE THREAD

**Issue by bk-cs** [CrowdStrike/psfalcon#158]
**Describe the bug**
Zero Trust Assessment results are not being properly added under the `zero_trust_assessment` property in a `Get-FalconHost` result.

**To Reproduce**
```
Get-FalconHost -Include zero_trust_assessment
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - PowerShell: 5.1
 - PSFalcon: 2.1.6

**Comment by bk-cs** [comment]
This issue is due to a typo that occured at some point. The following line in `Public\devices.ps1` is incorrect:

```
Object = $Result | Where-Object { $_.device_id -eq $Item.device_id }
```

The corrected version:
```
Object = $Result | Where-Object { $_.device_id -eq $Item.aid }
```

You can fix this problem yourself before the v2.1.7 release by replacing `Public\devices.ps1` with the contents of this file: https://raw.githubusercontent.com/CrowdStrike/psfalcon/master/Public/devices.ps1

**Comment by antmar904** [comment]
Great, thank you.  It is working now after updating devices.ps1.

Another question.  Would it be possible to add "All" when using the -Include parm to make it easier to I don't have to type in all the available args like "group_names,login_history,network_history,zero_trust_assessment" ?

**Comment by bk-cs** [comment]
Yes, it's possible to do so, but I'd rather make that change as `group_names` and `zero_trust_assessment` require permissions beyond `hosts:read`, and bundling them all together doesn't expose what the command is doing to the user in the same way that defining the options does. I don't want users to try `all` and not understand why they're getting errors.

If it helps, you can use your tab key to cycle through options until all are selected, or you can insert this into a script to gather all available values:

```
$Include = (Get-Command 'Get-FalconHost').ParameterSets.Where({ $_.Name -eq '/devices/queries/devices-scroll/v1:get' }).Parameters.Where({ $_.Name -eq 'Include' }).Attributes.ValidValues
```

Once defined, you can `-Include $Include`.

**Comment by bk-cs** [comment]
Closing due to [v2.1.7 release](https://github.com/CrowdStrike/psfalcon/releases/tag/2.1.7).
