### ISSUE TITLE
Error 403 Get-FalconHost PSFalcon 

### ISSUE THREAD

**Issue by alexmartin0800** [CrowdStrike/psfalcon#161]
Trying to achieve mass containment on PSFalcon and running into errors through the Get-FalconHost function

**Get-FalconHost -Filter "hostname:['_hostname_']" -Detailed | Select-Object hostname, device_id**

Upon testing the falcon token it returns true each time and despite a new session each attempt the error still occurs. a new API Key has been created with different and suitable read and write privilege's.

Write-Result : [{"code":403,"message":"access denied, authorization failed"}]

At C:\Program Files\WindowsPowerShell\Modules\PSFalcon\2.1.6\Private\Private.ps1:548 char:35

+ $Result = Write-Result $Request

+ ~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : NotSpecified: (System.Threadin...esponseMessage]:Task`1) [Write-Result], Exception

+ FullyQualifiedErrorId : Write-Result

**To Reproduce**
Run Windows Powershell ISE as Administrator on Remote Windows Server 2016.
Install PSFalcon
Update Module PSFalcon
Import Module PSFalcon
Request Falcon Token with API Key 
Test Falcon Token 
then run command in issue description

**Expected behavior**
Run and execute Get-FalconHost command correctly

**Environment (please complete the following information):**
 - OS: Windows Server 2016
 - PowerShell: 5.1
 - PSFalcon: 2.1.6

**Comment by bk-cs** [comment]
Can you run these commands and provide the output?

```
Import-Module PSFalcon
Show-FalconModule
```

I generally don't recommend installing the module as an administrator unless required. I've seen PowerShell have access issues with the module installed anywhere other than the `Users` folder. PSFalcon doesn't require any administrator privileges, which is why the installation instructions install it as a regular user account:

```
Install-Module -Name PSFalcon -Scope CurrentUser
```

**Comment by alexmartin0800** [comment]
![image](https://user-images.githubusercontent.com/97200988/148710636-eaaef4f5-814e-4367-8463-02664eba25ad.png)

Hi there here is the output you asked for, i decided to run this windows powershell ISE as my current user and i still get the same error as above.

**Comment by bk-cs** [comment]
Can you run outside of PowerShell ISE? I generally don't recommend using PowerShell ISE with PSFalcon as it is not tested for that environment and I have seen it produce intermittent issues.

Development of PowerShell ISE stopped back with PowerShell v6 and it's a good idea to move to Visual Studio Code if you're actively developing. 

You should also reset your ClientId and ClientSecret since they were included with the post. :)

**Comment by alexmartin0800** [comment]
Hi, i have tried running it outside of Powershell ISE and did in Visual Studio Code, however i still achieved the same result. i have attached the error message below.
![image](https://user-images.githubusercontent.com/97200988/149682345-a2b024d4-2d4f-4f4f-9b8d-792cf3c4c32e.png)

**Comment by bk-cs** [comment]
* Have you validated the permissions of your API client?
* Does your organization have IP-based filtering enabled for API access?

**Comment by alexmartin0800** [comment]
Shouldn't be any issue. We are using SIEM connector API on an azure VM for log collection. and have also validated the API permissions

**Comment by bk-cs** [comment]
Can you re-run the command and capture the `trace_id` value so I can do some investigating?

```
Request-FalconToken -ClientId <string> -ClientSecret <string>
$VerbosePreference = 'Continue'
Get-FalconHost -Filter "hostname:['hostname']" -Detailed  | Select-Object hostname, device_id
$Error.FullyQualifiedErrorId
```
The `trace_id` value should be present in the second line (`<trace_id>,Write-Result`).

**Comment by alexmartin0800** [comment]
PS C:\Users\admin_amartin> Request-FalconToken -ClientID +++++++++ -ClientSecret +++++++++++
VERBOSE: [ApiClient.Invoke] POST https://api.crowdstrike.com/oauth2/token
VERBOSE: [ApiClient.Invoke] ContentType: application/x-www-form-urlencoded, Accept: application/json
VERBOSE: [ApiClient.Invoke] 201: Created
VERBOSE: [Write-Result] Strict-Transport-Security=max-age=31536000; includeSubDomains, X-Cs-Region=us-1, 
X-Cs-Traceid=0685a4b8-fcf8-4885-9778-c8ae099b9581, X-Ratelimit-Limit=300, X-Ratelimit-Remaining=298, Date=Wed, 19 Jan 2022 
23:29:47 GMT
VERBOSE: [Request-FalconToken] Authorized until: 01/19/2022 23:59:46
PS C:\Users\admin_amartin> Test-FalconToken

Token Hostname                    ClientId                         MemberCid
----- --------                    --------                         ---------
 True https://api.crowdstrike.com 48c87c6da8a2406fb8c5e5cc8c7ec64a


PS C:\Users\admin_amartin> $VerbosePreference = 'Continue'
PS C:\Users\admin_amartin> Get-FalconHost -Filter "hostname:['++++++']" -Detailed  | Select-Object hostname, device_id
VERBOSE: [ApiClient.Invoke] GET https://api.crowdstrike.com/devices/queries/devices-scroll/v1?filter=hostname:['++++++']
VERBOSE: [ApiClient.Invoke] Accept: application/json
VERBOSE: [ApiClient.Invoke] 403: Forbidden
VERBOSE: [Write-Result] X-Content-Type-Options=nosniff, X-Ratelimit-Limit=15, X-Ratelimit-Remaining=14, Date=Wed, 19 Jan 2022 
23:30:51 GMT, meta.query_time=9.4E-08, meta.powered_by=crowdstrike-api-gateway
Write-Result : [{"code":403,"message":"access denied, authorization failed"}]
At C:\Program Files\WindowsPowerShell\Modules\PSFalcon\2.1.6\Private\Private.ps1:548 char:35
+                         $Result = Write-Result $Request
+                                   ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Threadin...esponseMessage]:Task`1) [Write-Result], Exception
    + FullyQualifiedErrorId : Write-Result
 
PS C:\Users\admin_amartin> $Error.FullyQualifiedErrorId
Write-Result
Write-Result
Write-Result
Write-Result
Write-Result
TypeNotFound

**Comment by alexmartin0800** [comment]
I have replaced sensitive information with '+'

**Comment by bk-cs** [comment]
* Can you confirm that your API client has `devices:read` (listed in the UI as "Hosts")?
* Can you create another API client to determine if you have the same problem?

**Comment by bk-cs** [comment]
Were you able to confirm the permissions for your API client? You'll need both `devices:read` and `devices:write` to find the hosts and contain them. I will close this issue in 48 hours unless you reply with more info. Thanks!

**Comment by alexmartin0800** [comment]
This worked! thank you :)
