### ISSUE TITLE
[ QUESTION ] ...Hello

### ISSUE THREAD

**Issue by sunesra** [CrowdStrike/psfalcon#165]
**Unable to export CrowdStrike configuration**
A clear and concise description of what the question is.

**To Reproduce**
Steps to reproduce the behavior you are seeing.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Windows Server 2016, Windows 10]
 - PowerShell: [e.g. 5.1]
 - PSFalcon: [e.g. 2.1.4]

**Additional context**

**Comment by sunesra** [comment]
Trying to Export CS Configuration and getting below error.
'/devices/combined/host-groups/v1?limit=500' is not a valid URL. Verify module installation.
At C:\Users\********\Documents\WindowsPowerShell\Modules\PSFalcon\2.0.8\Private\Private.ps1:915 char:13
+             throw "'$FullUri' is not a valid URL. Verify module insta ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ('/devices/combi...e installation.:String) [], RuntimeException
    + FullyQualifiedErrorId : '/devices/combined/host-groups/v1?limit=500' is not a valid URL. Verify module installat
   ion.

**Comment by bk-cs** [comment]
Based on the error, it looks like you are importing a very old version of PSFalcon. Can you delete all copies of the module on your system and re-install from the PowerShell Gallery?

```
Uninstall-Module -Name PSFalcon -AllVersions
```
https://github.com/CrowdStrike/psfalcon/wiki/Installation

**Comment by sunesra** [comment]
After new version still below error.
'/devices/combined/host-groups/v1?limit=500' is not a valid URL. Verify module installation.
At C:\Users\M7033766\Documents\WindowsPowerShell\Modules\PSFalcon\2.0.8\Private\Private.ps1:915 char:13
+             throw "'$FullUri' is not a valid URL. Verify module insta ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ('/devices/combi...e installation.:String) [], RuntimeException
    + FullyQualifiedErrorId : '/devices/combined/host-groups/v1?limit=500' is not a valid URL. Verify module installat
   ion.

**Comment by bk-cs** [comment]
I can tell from the error that you are not using the newest release (`2.1.6`):
```
C:\Users\M7033766\Documents\WindowsPowerShell\Modules\PSFalcon\2.0.8\Private\Private.ps1
```

The specific error that you're seeing is because parts of the module are not loading properly. There were some major changes after version `2.0.8` that should help resolve that, but you'll have to ensure you've got the proper version installed and imported before trying to `Get-FalconHostGroup`.

**Comment by sunesra** [comment]
Hello,

Thank you it works now.
Was very happy.
But we have having many different tenants, so i don't know if it will export from all tenant at one time? or it will only export from Primary tenant?

**Comment by bk-cs** [comment]
Short answer: it depends on what data you're looking to export. Some data lives in the parent CID, some data lives in the children. If it's not available in the parent, it needs to be pulled from the children.

https://github.com/CrowdStrike/psfalcon/wiki/Code-Examples#authorize-and-run-commands-in-member-cids
