### ISSUE TITLE
zero_trust_assessment

### ISSUE THREAD

**Issue by antmar904** [CrowdStrike/psfalcon#179]
Hi

I am using PSFalcon 2.1.7 and trying to pull the zero_trust_assessment value but it does not return anything.
Here are the returned results.

`zero_trust_assessment            : @{modified_time=2/7/2022 4:28:54 PM; sensor_file_status=confirmed; assessment=; assessment_items=}`

As you can see the "assessment=" is blank.

**Comment by bk-cs** [comment]
That's most likely due to the device itself having no assessment results. You can verify this using `Get-FalconZta`:

```
Get-FalconZta -Ids <id>```
