### ISSUE TITLE
[ BUG ] 'Invoke-FalconDeploy' does not start FFC on Mac/Linux

### ISSUE THREAD

**Issue by cwade18** [CrowdStrike/psfalcon#183]
**Description of your question**
.I am encountering a permissions issue when trying to set up and deploy Falcon. I reached out to Crowdstrike and this was their response "PSFalcon is not supported by the CrowdStrike Support Team, and we are unable to advise with issues relating to its use and configuration. If you are experiencing issues with PSFalcon, I would recommend raising an issue via the Github page".  When I Run the FalconDeploy on the imported list of hostids contained in the$HostIds variable, I expected for the command "Invoke-FalconDeploy -HostIds$ HostIds-Path<pathtoFFCbinary>  -QueueOffline $True" to deploy the executable to the host. I actually get an error message instead. I am concerned that i have the wrong version of the PSfalcon. 

**ERROR below:
**S /> Invoke-FalconDeploy -Help
Invoke-FalconDeploy: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided

PS /Users/xxxxxx/Downloads/Falcon_Forensics> Invoke-FalconDeploy -HostIds $HostIds -Path /Users/xxxxxx/Downloads/Falcon_Forensics/ffc -QueueOffline $True

Write-Result: /Users/xxxxxx/.local/share/powershell/Modules/PSFalcon/2.1.6/Private/Private.ps1:548

Line |

 548 |                          $Result = Write-Result $Request

     |                                    ~~~~~~~~~~~~~~~~~~~~~

     | [{"code":403,"message":"access denied, authorization failed"}]****

**To Reproduce**
1. Load PSFalcon modules.
Import-ModulePSFalcon

2. Display the list of imported hosts.
$HostIds
    
3. Import only the“HostID”column of your csv file.
$HostIds=(Import-Csv./hostids.csv).'HostID'

4. Use the API keys to request a token.
Request-FalconTokenClienID: <string>ClientSecret: <string> (WORKS)

5. See the help file for FalconDeploy. 
Invoke-FalconDeploy-Help. (DOES NOT WORK)

6. RunFalconDeploy on the imported list of hostids contained in the$HostIds variable. Replace<path to FFC binary>with the full path to the saved binary on your computer. Note: Relative paths are banned in this step. You can't use “.” to reference the current working directory.
Invoke-FalconDeploy -HostIds$ HostIds-Path<pathtoFFCbinary>  -QueueOffline $True.  (DOES NOT WORK)

**Expected behavior**
To deploy the executable to the host.

**Environment (please complete the following information):**
![Screen Shot 2022-02-09 at 8 22 14 AM](https://user-images.githubusercontent.com/99349803/153247772-becbcfd3-f9fc-411e-a426-d06d4e7a706c.png)

 - OS: macOS Big Sur
 - PowerShell: 7.2.1
 - PSFalcon: 2.1.7

**Additional context**

**Comment by bk-cs** [comment]
I believe we talked about this over email, and that your API client is missing the required permissions for `Invoke-FalconDeploy`. The required permissions for each command can be found here: https://github.com/CrowdStrike/psfalcon/wiki/Permissions

Please let me know if updating your permissions does not solve the issue for you.

**Comment by cwade18** [comment]
Thanks,

So, I deployed the fcc file to a test mac and got the output below. I did this at 8am (5 hrs ago). Nothing showed in the forensic dashboard. So, I am not sure what else to do here. I ran the queue command to see the status and nothing. Am I missing something?

[cid:3acb6e38-0686-442d-af80-94fa6254d0a9]
________________________________

**Comment by bk-cs** [comment]
That looks like output that came from Real-time Response, suggesting that it was run successfully.

* Do you have access to Forensics in your Falcon console?
* Does that `cid` value that was output match the CID that you have access to when you log in to the Falcon console? Forensics will default to the CID that the device is assigned to.

**Comment by cwade18** [comment]
Yes, I have access to the console but I am not sure where to find the cid to even compare.

**Comment by cwade18** [comment]
Another question, when I use the following command " Invoke-FalconDeploy -HostIds $HostIds -Path /Users/xxxxx/Downloads/Falcon_Forensics/ffc -QueueOffline $True" to deploy the files, it creates a csv file that contains this error.  "File exists and overwrite not requested." I am not sure what that implies.

**Comment by cwade18** [comment]
Maybe i am missing something or doing something incorrectly.

**Comment by bk-cs** [comment]
No, you're not doing something incorrectly--`Invoke-FalconDeploy` is. Up until now, I didn't know that the Mac and Linux versions of FFC require some input when they're executed. Windows doesn't, so `Invoke-FalconDeploy` runs the executable without any parameters.

In the case of Linux/Mac, this would lead to FFC not doing anything, and leaving the executable in the temp directory. That's the reason you're getting the `File exists and overwrite not requested.` error; when you try `Invoke-FalconDeploy` and the file is already there, it doesn't continue.

I'll need to edit the command to add in the additional parameter for Mac/Linux. I'm working on that now.

**Comment by cwade18** [comment]
Thank you. I will try this now.

**Comment by cwade18** [comment]
Hi,

So I made the recommended changes to  the permissions, ran the command but got a different error. 
<img width="980" alt="Screen Shot 2022-02-15 at 8 35 38 AM" src="https://user-images.githubusercontent.com/99349803/154106892-fd861630-084c-4dbc-8c4a-e7b0aae12b7d.png">

**Comment by bk-cs** [comment]
You need to verify that the `run` command is enabled in the Real-time Response policy that is assigned to the target devices.
