### ISSUE TITLE
[ BUG ] Get-FalconDetection Filter 'Severity' Returns no Data

### ISSUE THREAD

**Issue by oracle701** [CrowdStrike/psfalcon#184]
**Describe the bug:**
The Filter 'severity' returns nothing for Get-FalconDetection. I don't get an error, just no results.
I have confirmed the API I am using contains Detection:Read.

**To Reproduce"**
Get-FalconDetection -Filter "severity:'low'" - No data returned for this, and all other severities. 

**Expected behavior:**
I would expect all low detections would be listed for the above example. The Filter works for other properties like status and last_seen.

**Environment:**
 - OS: Windows 10\Server 2019
 - PowerShell: 7.2\5.1
 - PSFalcon: 2.1.7

**Comment by bk-cs** [comment]
This is not a PSFalcon issue; `severity` is not a valid filter for the detections API. See the detections API documentation for more details. \[ [US-1](https://falcon.crowdstrike.com/documentation/86/detections-monitoring-apis#find-detections) | [US-2](https://falcon.us-2.crowdstrike.com/documentation/86/detections-monitoring-apis#find-detections) | [US-GOV-1](https://falcon.laggar.gcw.crowdstrike.com/documentation/86/detections-monitoring-apis#find-detections) | [EU-1](https://falcon.eu-1.crowdstrike.com/documentation/86/detections-monitoring-apis#find-detections) \]

The filter property you're looking for is `max_severity_displayname`. The API should be returning an error code for using `severity`, but that's an issue with the API itself and not PSFalcon.
