### ISSUE TITLE
PSFalcon API Error 403

### ISSUE THREAD

**Issue by alexmartin0800** [CrowdStrike/psfalcon#188]
Hi there, we are currently facing an issue with our PSFalcon API connection, previously we have been using it for Mass Containment and Mass RTR on our jumphost server, however today after trying to conduct some more script writing the API appears to have failed authenticating. all the settings and privilege's have remained the same the entire lifespan of the API token. is there anything that could have happened with the account being used to authenticate the token or is it an issue with the API itself. 

Any help would be much appreciated. I have attached and image of the API failing to authenticate.

Thanks - Alex

![Screenshot 2022-03-16 114223](https://user-images.githubusercontent.com/97200988/158495301-ed7e8376-89ba-4e71-8f4d-1b40b7a56ae7.jpg)

**Comment by bk-cs** [comment]
* Are you using the US-1 cloud?
 
That's the default if you don't specify `-Hostname` or `-Cloud` when using `Request-FalconToken`. Although you should be redirected, it may not always work (especially if your cloud is `US-GOV-1`).

* Can you reset your API client and try again?

* Can you remove PSFalcon v2.1.6 and install v2.1.7?

**Comment by alexmartin0800** [comment]
Issue was resolved when resetting the API

Thanks for your assistance
