### ISSUE TITLE
[ BUG ] Import-FalconConfig failing for IOA Exclusions

### ISSUE THREAD

**Issue by csuser251** [CrowdStrike/psfalcon#192]
**Describe the bug**
The Import-FalconConfig command is failing with `WARNING: Unable to create 'Test' [missing_assignment]` when Importing IOA exclusions, respectively with the following error if using the `-Force` flag

```
Get-ConfigItem : Cannot bind parameter because parameter 'Type' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
At C:\Program Files\WindowsPowerShell\Modules\PSFalcon\2.1.8\Public\psf-config.ps1:475 char:57
+                                 ,(Get-ConfigItem @Param -Type 'Cid'). ...
+                                                         ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ConfigItem], ParameterBindingException
    + FullyQualifiedErrorId : ParameterAlreadyBound,Get-ConfigItem

Get-ConfigItem : Cannot bind parameter because parameter 'Type' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
At C:\Program Files\WindowsPowerShell\Modules\PSFalcon\2.1.8\Public\psf-config.ps1:475 char:57
+                                 ,(Get-ConfigItem @Param -Type 'Cid'). ...
+                                                         ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ConfigItem], ParameterBindingException
    + FullyQualifiedErrorId : ParameterAlreadyBound,Get-ConfigItem
```

**To Reproduce**
Try to import the attached .zip containing sample IOA Exclusions via `Import-FalconConfig .\FalconImportIoaExclusion.zip` or `Import-FalconConfig .\FalconImportIoaExclusion.zip -Force`

[FalconImportIoaExclusion.zip](https://github.com/CrowdStrike/psfalcon/files/8331798/FalconImportIoaExclusion.zip)

The hostgroups referenced in the IOA exclusions are not present in the target CID, but I've also tried creating matching hostgroups (based on Host Group Name and Assignment Rule) before performing the `Import-FalconConfig` and I get the same error.

**Expected behavior**
Host groups should be created in case they are not already present and the IOA exclusions should be successfully imported.

**Environment:**
 - OS: Windows 10
 - PowerShell: 5.1
 - PSFalcon: 2.1.7 and 2.1.8
- The API Key has the following scopes: Host groups read/write, IOA Exclusions read/write

 
**Transcript content**
[PowerShell_transcript.DESKTOP-2B244PN.ROlMzyHR.20220323101112.txt](https://github.com/CrowdStrike/psfalcon/files/8331792/PowerShell_transcript.DESKTOP-2B244PN.ROlMzyHR.20220323101112.txt)

**Comment by bk-cs** [comment]
Thank you for the report. It may take me a little bit to get to this one, but I have it on my list.

**Comment by bk-cs** [comment]
I'm re-writing a lot of `Import-FalconConfig` with the planned changes for the next version of PSFalcon. I'll make sure to get this fixed at the same time.

**Comment by bk-cs** [comment]
I've put out a non-production release of the next version of PSFalcon. Could you give `Import-FalconConfig` a try using 2.2.0-beta1 and let me know if it solves the issue?

https://github.com/CrowdStrike/psfalcon/releases/tag/2.2.0

**Comment by bk-cs** [comment]
The official v2.2.0 release is now available and I expect that it resolves this issue. Please let me know once you're able to test, and I'll close this in a few days if I don't hear back.
