### ISSUE TITLE
Invoke-FalconRtr : How to run a local complexe PS Script

### ISSUE THREAD

**Issue by egl35720** [CrowdStrike/psfalcon#201]
Good afternoon to all,

I want to run a complexe PS Script that I have uploaded into the cloud using 
`Invoke-FalconRtr -Command runscript -Arguments "-CloudFile='Deploy-LAPS'" -Timeout '600' -HostIds $HOSTID`
this command returns the result below

complete         : True
offline_queued   : False
errors           : 
stderr           : Exception setting "CursorPosition": "A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host 
                   program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do 
                   not support user interaction, such as Windows PowerShell workflows."Cannot convert argument "fill", with value: "System.Collections.Hashtable", for "SetBufferContents" to 
                   type "System.Management.Automation.Host.BufferCell": "Cannot create object of type "System.Management.Automation.Host.BufferCell". Cannot convert null to type 
                   "System.ConsoleColor" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are 
                   "Black;DarkBlue;DarkGreen;DarkCyan;DarkRed;DarkMagenta;DarkYellow;Gray;DarkGray;Blue;Green;Cyan;Red;Magenta;Yellow;White"."
stdout           : 

But I don't understand this sterr.

The script named "Deploy-LAPS.ps1" use many functions on the target machine, to check OS compliance, If the desired package "LAPS CSE" is already installed or not, call a function to installe LAPS CSE using msiexec, log its different steps, and if installation occured, check and log into its own log the result of MSIEXEC installation.

**Comment by egl35720** [comment]
Thank you bk-cs,

this is why I am very surpised, when I run this script localy it works fine. It doesn't require any action in user space.

**Comment by bk-cs** [comment]
Unfortunately, local execution is not a comparison because RTR isn't the same as a local PowerShell session. Does the script work if you attempt to execute it on a device remotely using PSExec or `Enter-PsSession`?

**Comment by egl35720** [comment]
I'll try tomorrow afternoon

**Comment by bk-cs** [comment]
Would you also be able to share the script itself, if it's something I would be able to test on a non-domain joined virtual machine?

**Comment by egl35720** [comment]
Yes, I can share you the script Deploy-LAPS.ps1 uploaded on the Cloud and the local script I run from my workstation to call Deploy-LAPS.ps1 to Target machine. How can I share you these 2 scripts ?
And yes the script can be run on a WORKGROUP machine.

Otherwise here below my test running Deploy-LAPS.ps1 from my workstation using PSSESSION :
`$PSESSION = New-PSSession -ComputerName RTH-SV-VEEAM-1.ad.groupeavril.com -Credential (Get-Credential)

Invoke-Command -Session $PSESSION -ScriptBlock {C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe c:\sources\Deploy-LAPS.ps1}`

Deploy-LAPS.ps1 in this case works fine here is the DeployLAPS.log 
[13/04/2022-17:45:23] - [INFO] - TARGET MACHINE HOSTNAME : RTH-SV-VEEAM-1
[13/04/2022-17:45:23] - [INFO] - TARGET MACHINE DOMAIN NAME : ad.groupeavril.com
[13/04/2022-17:45:23] - [INFO] - TARGET MACHINE OS TYPE : 18
[13/04/2022-17:45:23] - [INFO] - TARGET MACHINE OS VERSION: 6.1.7601
[13/04/2022-17:45:23] - [INFO] - TARGET MACHINE OS DESCRIPTION : Microsoft Windows Server 2008 R2 Standard 
[13/04/2022-17:45:23] - [INFO] - TARGET MACHINE OS ARCHITECTURE : 64 bits
[13/04/2022-17:45:23] - [INFO] - TARGET MACHINE OS SUPPORTED : OK
[13/04/2022-17:45:23] - [INFO] - LAPS CLIENT SIDE EXTENSION (AdmPwd.dll) INSTALLATION FUNCTION CALL
[13/04/2022-17:47:20] - [INFO] - LAPS CLIENT SIDE EXTENSION ALREADY INSTALLED. NO ACTION NEEDED.

**Comment by egl35720** [comment]
[Deploy-LAPS.ps1.txt](https://github.com/CrowdStrike/psfalcon/files/8482908/Deploy-LAPS.ps1.txt)
[RunFalconScript-Deploy-LAPS.ps1.txt](https://github.com/CrowdStrike/psfalcon/files/8482920/RunFalconScript-Deploy-LAPS.ps1.txt)

**Comment by egl35720** [comment]
@bk-cs thanks a lot for your help.

Have a good evening

**Comment by bk-cs** [comment]
Did you get this working? Sorry, I did not have a chance to test the script myself.

**Comment by egl35720** [comment]
@bk-cs Yes I found a workarround copying Deploy-LAPS.ps1 on target machine via PSFalcon so I used PSSEssion to run Deploy-LAPS.ps1 on it.
It works fine
