### ISSUE TITLE
[ DOC ] Typo in wiki for falcon grouping tags

### ISSUE THREAD

**Issue by thebluetoob** [CrowdStrike/psfalcon#216]
**Describe the bug**
The wiki entry for ["Adding Falcon grouping tags"](https://github.com/CrowdStrike/psfalcon/wiki/Host-and-Host-Group-Management#adding-falcon-grouping-tags) specifies `-Tags FalconGroupingTag/tag1` which [fails validation of the regex](https://github.com/CrowdStrike/psfalcon/blob/master/Public/devices.ps1#L17) which requires `-Tags FalconGroupingTags/tag1` with an `s` on the end

**To Reproduce**
Either make an API call with the line copied from the documentation or compare the regular expression on line 17 of /Public/devices.ps1

**Expected behavior**
The example provided in the documentation to pass the regular expression check

**Environment (please complete the following information):**
 - OS: Windows 10
 - PowerShell: 5.1.19041.1682
 - PSFalcon: 2.2

I would've raised a PR instead of an issue but unfortunately Github doesn't support PR's for wikis.

Thanks!

**Comment by jshcodes** [comment]
Hi @thebluetoob -

I've updated this page to reflect the correction.  Thank you for reporting this!  :smile:

**Comment by thebluetoob** [comment]
Thank you! Apologies for the poor title tag, wasn't sure how best to tag it.

**Comment by jshcodes** [comment]
No worries!  You got it reported, that's what's important. :smile:
