### ISSUE TITLE
[ BUG ] `Get-FalconRole`: Parameter set cannot be resolved using the specified named parameter

### ISSUE THREAD

**Issue by jass4l** [CrowdStrike/psfalcon#240]
**Describe the bug**
Getting `Get-FalconRole : Parameter set cannot be resolved using the specified named parameters` error while running a script with command `$falconrole = Get-FalconRole -User Id "$falconuuid" -Detailed`

I'm not the author of the script so can't prove much information but from the error, the issue could be related to how variables are declared in the above command. Though, the same script runs without any issue on PSFalcon 2.2.1 and my presumption is that PSFalcon 2.2.2 has some changes that's messing this up.

**To Reproduce**
Set the parameters/declare variable
Run the command

**Expected behavior**
Show the falcon role of the user(s)

**Environment (please complete the following information):**
 - OS: Windows 10
 - PowerShell: 5.1
 - PSFalcon: 2.2.2
 
**Transcript content**
```
Get-FalconRole : Parameter set cannot be resolved using the specified named parameters.
At C: \Users\Documents\WindowsPowerShell\Scripts\script.ps1:159 char :19
  $falconrole = Get-FalconRole -User Id "$falconuuid" -Detailed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CategoryInfo : InvalidArgument: (:) [Get-FalconRole], ParameterBindingException
  FullyQualifiedErrorId : AmbiguousParameterSet,Get-FalconRole
```

**Comment by bk-cs** [comment]
The error is due to a command change that I did not document. `Get-FalconRole` uses a new API endpoint which already has detailed information included, so `-Detailed` is no longer required.

Try changing the following line:
```
$falconrole = Get-FalconRole -UserId "$falconuuid" -Detailed
```
To:
```
$falconrole = Get-FalconRole -UserId "$falconuuid"
```

**Comment by jass4l** [comment]
Thanks for the solution. I've let the script owner know about the suggested solution. Once they modify the script, I'll report back as soon as I can.

**Comment by bk-cs** [comment]
Thank you!

Given that the resolution appears to require no changes to the PSFalcon module itself, I will close this issue at the end of the week unless the script change does not resolve the problem.
