### ISSUE TITLE
[ BUG ] `Import-FalconConfig` failing on PowerShell Core with `Key cannot be null` error

### ISSUE THREAD

**Issue by quantmn5** [CrowdStrike/psfalcon#241]
**Describe the bug**
I'm still facing issues with build 2.2.2 while importing a previously exported falcon-config.
Importing host-groups, prevention policy and response policies are all failing.
I try to import a config-export for a freshly provisioned Customer ID (no config set besides default prevention policies).

Not sure if i'm doing anything wrong here.. it all worked fine in the second last version. PSFalcon 2.2.1 did not work, neither is the current version.

**To Reproduce**
Simply using the import-FalconConfig with or without -assignexisting /-modifyexisting / -modifydefault flags results in the errors you can find in the attached screenshot.

**Expected behavior**
I expect the config to be imported properly.

**Environment (please complete the following information):**
 - OS: Windows11
 - PowerShell: 7.2.6
 - PSFalcon: 2.2.2

![Import_Config](https://user-images.githubusercontent.com/113588206/190356025-9de7b6a9-fe21-4125-a9be-9f3d6fd5d662.png)
 **Additional context**

 
**Transcript content**
Invoke-FalconPreventionPolicyAction: C:\Users\username\Documents\Powershell\Modules\PSFalcon\2.2.2\Public\psf.config.ps1:340

$PolicyID | & "Invoke-Falcon$($Type)Action" -Name $Action
Cannot validate argument on parameter 'Id'. The argument " " does not match the "^[a-fA-F0-9]${32}$" pattern.
Supply an argument that matches "^[a-fA-F0-9]${32}$" and try again.

**Comment by bk-cs** [comment]
This appears to be restricted to PowerShell Core. Can you re-try with PowerShell Desktop? It is still the default PowerShell version on Windows 11.

**Comment by bk-cs** [comment]
Leaving open in case others run into this issue before the 2.2.3 release.

**Comment by bk-cs** [comment]
Resolved in v2.2.3 release.
