### ISSUE TITLE
[ BUG ] syntax error in documentation

### ISSUE THREAD

**Issue by mbonne-mc** [CrowdStrike/psfalcon#245]
**Describe the bug**
Documentation error. Shows incorrect syntax in example? or it changed? (https://github.com/CrowdStrike/psfalcon/wiki/Detection-and-Prevention-Policies#assign-host-groups-to-policies)

**To Reproduce**
Typed command into powershell and got error: 
Invoke-FalconPreventionPolicyAction: A parameter cannot be found that matches parameter name 'ActionName'.

**Expected behavior**
Add host group to prevention policy via id of both.

**Environment (please complete the following information):**
 - OS: macOS
 - PowerShell: core - 7.2.6
 - PSFalcon: 2.2.2

**Additional context**
when typing 'Invoke-FalconPreventionPolicyAction' on its own, noticed it referenced 'Name' not 'ActionName'

changed syntax to: Invoke-FalconPreventionPolicyAction -Name add-host-group -Id <id> -GroupId <id>
 and worked as expected.

**Comment by bk-cs** [comment]
Corrected, thanks!
