### ISSUE TITLE
Installation Wiki Move-Item command limitations

### ISSUE THREAD

**Issue by n2x4** [CrowdStrike/psfalcon#26]
Just wanted to mention that the linux commands listed in the wiki for moving the master repo folder into the powershell module directory can fail with an error "Could not find a part of the path ...."  I recognize that -Force should help with this, but in my testing this was not the case.  Manually creating the PSFalcon/<version> directory allows you to then use the move-item command without an error.

This was reproduced in PowerShell 7.0.0 on Kali

**Comment by bk-cs** [comment]
Thank you for the clarification. I'll add a note to the wiki.
