### ISSUE TITLE
[ BUG ] Get-FalconUninstallToken returns Invalid JSON primitive

### ISSUE THREAD

**Issue by DiskIOinferno** [CrowdStrike/psfalcon#280]
**Describe the bug**
Get-FalconUninstallToken does not return the uninstall token for a specified host and instead returns an `Invoke-Falcon : Invalid JSON primitive` error

**To Reproduce**
- Get a token using `Request-FalconToken` submitting ClientID and Secret when prompted
- Confirm `Test-FalconToken` returns True
- Get the HostID using `Get-FalconHost -filter "hostname:myhostname'"`
- Run `Get-FalconUninstallToken -Id myhostid`

**Expected behavior**
After running `Get-FalconUninstallToken -Id myhostid`, psfalcon should print the uninstall token to stdout

**Environment (please complete the following information):**
 - OS: Windows 10
 - PowerShell: 5.1
 - PSFalcon: 2.2.2

**Additional context**
This was known to work as described within the last 1-2 days
 
**Transcript content**

usernames, partial paths, device_id, host_id, and hostname have been redacted

**********************
Windows PowerShell transcript start
Start time: 20230209205114
Username: domain\samaccountname
RunAs User: domain\samaccountname
Configuration Name: 
Machine: localhost (Microsoft Windows NT 10.0.19042.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 8096
PSVersion: 5.1.19041.2364
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.2364
BuildVersion: 10.0.19041.2364
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\userpath\PowerShell_transcript.L025929121257.khA8EPwn.20230209205114.txt
PS C:\Users\username> Get-Falconhost -filter "hostname:'myhostname'"
VERBOSE: [ApiClient.Invoke] GET https://api.crowdstrike.com/devices/queries/devices-scroll/v1?filter=hostname:'myhostname'
VERBOSE: [ApiClient.Invoke] Accept=application/json
VERBOSE: [ApiClient.Invoke] 200: OK
VERBOSE: [ApiClient.Invoke] Connection=keep-alive, Strict-Transport-Security=max-age=15724800; includeSubDomains, max-age=31536000; includeSubDomains, X-Cs-Region=us-1, X-Cs-Traceid=0a851841-761b-400a-81b0-bbe2766f0630, X-Ratelimit-Limit=6000, X-Ratelimit-Remaining=5997, Date=Thu, 09 Feb 2023 09:51:20 GMT, Server=nginx
VERBOSE: [Write-Result] meta.powered_by=device-api, meta.pagination.total=1, meta.pagination.offset=DnF1ZXJ5VGhlbkZldGNoAgAAAALBmIWFFmIzdUhrSHh0UXRtLVd5YmYzam81cFEAAAAAA8wBlhZQSXhGbTJrTlN2V1B2ajIyRzJPbU9R, meta.pagination.expires_at=1675936400293445045, meta.trace_id=0a851841-761b-400a-81b0-bbe2766f0630, meta.query_time=0.003890777
returned_device_id
PS C:\Users\username> Get-FalconUninstallToken -Id returned_device_id
VERBOSE: [ApiClient.Invoke] POST https://api.crowdstrike.com/policy/combined/reveal-uninstall-token/v1
VERBOSE: [ApiClient.Invoke] ContentType=application/json, Accept=application/json
VERBOSE: [ApiClient.Invoke] {"device_id":"returned_device_id"}
VERBOSE: [ApiClient.Invoke] 200: OK
VERBOSE: [ApiClient.Invoke] Connection=keep-alive, Strict-Transport-Security=max-age=15724800; includeSubDomains, max-age=31536000; includeSubDomains, X-Cs-Region=us-1, X-Cs-Traceid=028a86e8-2b8c-414e-a592-2d16c2d5ee77, X-Ratelimit-Limit=6000, X-Ratelimit-Remaining=5996, Date=Thu, 09 Feb 2023 09:51:26 GMT, Server=nginx
PS C:\Users\username> TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
Invoke-Falcon : Invalid JSON primitive: .
At C:\userpath\WindowsPowerShell\Modules\psfalcon\2.2.2\Public\policy-sensor-update.ps1:366 char:25
+ ...   foreach ($r in (Invoke-Falcon @Param -Inputs $PSBoundParameters)) {
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Falcon
Invoke-Falcon : Invalid JSON primitive: .
At C:\Users\userpath\WindowsPowerShell\Modules\psfalcon\2.2.2\Public\policy-sensor-update.ps1:366 char:25
+ ...   foreach ($r in (Invoke-Falcon @Param -Inputs $PSBoundParameters)) {
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Falcon

PS C:\Users\username> Stop-Transcript
**********************
Windows PowerShell transcript end
End time: 20230209205137
**********************

**Comment by bk-cs** [comment]
This was an API issue and affected all Falcon SDKs.
