### ISSUE TITLE
Edit-FalconDeviceControlPolicy - end_user_notifications & enhanced_file_metadata - Not applying

### ISSUE THREAD

**Issue by jraph77** [CrowdStrike/psfalcon#286]
**Describe the bug**
Hi, 
The Edit-FalconDeviceControlPolicy doesn't apply the end_user_notifications = 'NOTIFY_USER' and the enhanced_file_metadata='True' settings.
enforcement_mode = 'MONITOR_ONLY' or enforcement_mode = 'MONITOR_ENFORCE' are correctly applied to the policy.

**To Reproduce**
$Setting = @{
        enforcement_mode = 'MONITOR_ENFORCE'
        end_user_notifications = 'NOTIFY_USER'
        enhanced_file_metadata='True'
}
Edit-FalconDeviceControlPolicy -Id <ID> -settings $Setting
Still return 
settings           : @{enforcement_mode=MONITOR_ENFORCE; end_user_notification=SILENT; custom_notifications=; classes=System.Object[]; enhanced_file_metadata=False}

**Expected behavior**
Get-FalconDeviceControlPolicy results on a policy where these settings are enabled on the GUI
enforcement_mode       : MONITOR_ENFORCE
end_user_notification  : NOTIFY_USER
enhanced_file_metadata : True

**Environment (please complete the following information):**
 - OS:  Windows 10
 - PowerShell: 5.1
 - PSFalcon: 2.2.4

**Comment by bk-cs** [comment]
I'm unable to recreate this using PowerShell 5.1 and Windows 11. These examples all behave as expected:

```
Edit-FalconDeviceControlPolicy -Id <id> -Setting @{ enforcement_mode = 'MONITOR_ENFORCE'; end_user_notification = 'NOTIFY_USER'; enhanced_file_metadata = $true }
```
```
$Policy = Get-FalconDeviceControlPolicy -Filter "name:'my_policy'" -Detailed
$Policy.settings.enforcement_mode = 'MONITOR_ENFORCE'
$Policy.settings.end_user_notification = 'NOTIFY_USER'
Edit-FalconDeviceControlPolicy -Id $Policy.id -Setting $Policy.settings
```
```
$Policy = Get-FalconDeviceControlPolicy -Filter "name:'my_policy'" -Detailed
$Policy.settings.enforcement_mode = 'MONITOR_ENFORCE'
$Policy.settings.end_user_notification = 'NOTIFY_USER'
$Policy | Edit-FalconDeviceControlPolicy
```
Are you still seeing the same behavior? Could something else be causing the issue?
