### ISSUE TITLE
[ WIKI ] Example script for sensor downloads generates error

### ISSUE THREAD

**Issue by MrBadRomance** [CrowdStrike/psfalcon#288]
Windows sensor download code is broken.
$Match variable is now a system object instead of a string

 $Match = try {
                # Select matching installer from list for 'platform_name' using regex pattern
                Get-FalconInstaller -Filter "platform:'$($Policy.platform_name.ToLower())'" -Detailed |
                    Where-Object { $_.version -match $Pattern -and $_.description -match 'Falcon Sensor' }
            } catch {
                throw 'Unable to find installer through version match'
            }

When you do **$Match.name** the out put are 2 Object names:
WindowsSensor.MaverickGyr.exe
WindowsSensor.MaverickGyr.exe

So the code followed would break because **$Match.name** is array not a string

Join-Path : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'ChildPath'. Specified method is not supported.
At line:25 char:74

            if ($Match.sha256 -and $Match.name) {
                $Installer = Join-Path -Path "C:\PowerShell\" -ChildPath $Match.name
                if ((Test-Path $Installer) -and ((Get-FileHash -Algorithm SHA256 -Path $Installer) -eq $Match.sha256)) {
                    # Abort if matching file already exists
                    throw "File exists with matching hash [$($Match.sha256)]"
                } elseif (Test-Path $Installer) {
                    # Remove other versions
                    Remove-Item -Path $Installer -Force
                }

This code works when you change the platform name to macOS.

**Comment by bk-cs** [comment]
Can you give a sample of the syntax you're using when you run the example script? I assume you're talking about this one:

https://github.com/CrowdStrike/psfalcon/wiki/Basic-Scripts#download-the-installer-package-assigned-to-a-sensor-update-policy

**Comment by MrBadRomance** [comment]
Yes that one and this one
https://github.com/CrowdStrike/psfalcon/wiki/Basic-Scripts#download-the-installer-package-assigned-to-your-default-sensor-update-policy

I ran the exact script today I am not getting any error.
I notice the difference for **$Match.name** return value

Today's output:
WindowsSensor.MaverickGyr.exe

Yesterday output:
WindowsSensor.MaverickGyr.exe
WindowsSensor.MaverickGyr.exe

This only occurred for Windows platform

**Comment by bk-cs** [comment]
Thanks! It's about time to do a pass through the script examples and see if they all can be updated. I'll see if I can improve the sensor download examples so that they only return a single value.

**Comment by bk-cs** [comment]
I went back through and tested this sample and was unable to recreate the issue. My guess is that this was a temporary problem due to multiple results showing for a particular sensor version at the time the original test was run (which can happen for a short period of time as new sensor versions are released).
