### ISSUE TITLE
[ QUESTION ] How to get processor architecture?

### ISSUE THREAD

**Issue by evild3ad** [CrowdStrike/psfalcon#289]
**Description of your question**
What is the best way to get the processor architecture of endpoints to deploy for example the correct binary?
  
I am currently using following command to get this information (works only when the endpoints are online):  
`$ARCH = (Invoke-FalconRtr runscript '-Raw=```$env:PROCESSOR_ARCHITECTURE```' -HostIds $device_id -ErrorAction SilentlyContinue).stdout`
  
It would be very helpful when the processor architecture would be available via `Get-FalconHost` and `Get-FalconHostGroupMember`, so that this information is available also when a host is temporarily offline. 

**Environment (please complete the following information):**
 - OS: macOS Ventura 13.2.1 (ARM64)
 - PowerShell: 7.3.3
 - PSFalcon: 2.2.4

Thank you!

**Comment by bk-cs** [comment]
PSFalcon delivers the data that's provided by the APIs. The APIs that power `Get-FalconHost` and `Get-FalconHostGroupMember` do not provide the processor architecture. If you'd like to see that in the output, I recommend opening an "idea" through your Falcon console and asking for it to be included as a property.

\[ [US-1](https://us-1.ideas.crowdstrike.com/) | [US-2](https://us-2.ideas.crowdstrike.com/) | [EU-1](https://eu-1.ideas.crowdstrike.com/) | [US-GOV-1](https://us-gov-1.ideas.crowdstrike.com/) \]

The `cpu_signature` property that is returned in the current response _might_ be able to be decoded to retrieve the processor bit level. I don't know enough about the data to know for sure.
