### ISSUE TITLE
Error when outputting Get-FalconFirewallEvent with -All to CSV

### ISSUE THREAD

**Issue by NoahDurham** [CrowdStrike/psfalcon#29]
I'm attempting to pull firewall events via script with API since the console only gives the latest 100 events when downloading a CSV from there. If I run the command without `-All` there are no errors but once I add `-All` I get the below error.

![image](https://user-images.githubusercontent.com/79472233/108748510-ad26f180-750c-11eb-95d7-bbc7a7739dc6.png)

My environment is in us-2.

**Comment by bk-cs** [comment]
I'm unable to recreate this in my testing. Entering in the exact same string completes the export with no errors (using PowerShell 5.1 on Windows 10).

Can you add some additional information?

1. Are you using the latest version of PSFalcon?
2. Can you set `$VerbosePreference` and `$DebugPreference` to `'Continue'`, `Start-Transcript`, `Show-FalconModule`, re-run your command(s), then finish with `Stop-Transcript` to capture detailed information?

Thanks!

**Comment by NoahDurham** [comment]
I updated my PSFalcon module from 2.0.0 to 2.0.5, set `$VerbosePreference` and $DebugPreference` to `'Continue'` and started a transcript to look deeper into what's going on. PowerShell errored when trying to run `Show-FalconModule` stating that the command did not exist.

What I found is that after every 100 events from the firewall, the API will throw the original post error and then pull the next 100 events. PowerShell will give the error 100 times as the max limit seems to be 10000 events. The script is seemingly finishing without any major issue.

Is there a way around the 10000 event limitation currently or is that a limitation of the API?

**Comment by bk-cs** [comment]
When updating, try deleting all PSFalcon files and re-installing fresh. If you are updating to v2.0.5, `Show-FalconModule` should be available. Because it isn't, it makes me believe that something went wrong when files were being placed into the module folder.

It sounds like the `Invoke-Loop` function (which the module uses to handle pagination) is running into a problem or not passing the proper `after` token. This is another indicator that the files aren't loading properly when the module is being imported.

Besides those two potential issues, there is no way around the 10,000 event limit as that's typically imposed by the API (not PSFalcon).

**Comment by NoahDurham** [comment]
I've done a fresh install of the PSFalson Module and it shows to be 2.0.5 now:

![image](https://user-images.githubusercontent.com/79472233/108889495-728b8a80-75da-11eb-84fd-0c679aa6eeff.png)

Now when testing the command or running my script I get thrown this error:

![image](https://user-images.githubusercontent.com/79472233/108890823-07db4e80-75dc-11eb-90d9-fe3bbbf1d61d.png)

It seems to coincide with your response about the `after` token as after setting the `$VerbosePreference` and checking the output transcript file I see the error after every `Invoke-Loop` shows that 100 results were retrieved.

**Comment by bk-cs** [comment]
Thanks! This error makes more sense. `Get-FalconFirewallEvent` does not have the `-After` parameter in v2.0.5. I'll fix this shortly...

**Comment by bk-cs** [comment]
Ok, please remove v2.0.5 and download v2.0.6 and re-test. I expect that it will fix your issue. Thanks!

**Comment by NoahDurham** [comment]
That fixed it! Thanks for your help and prompt responses!
