### ISSUE TITLE
[ BUG ] `Get-FalconQueue` no longer reporting queued sessions

### ISSUE THREAD

**Issue by PewlettHackard** [CrowdStrike/psfalcon#294]
**Describe the bug**
Despite a hefty list of offline hosts within Falcon; these are not added to the offline queue in PSFalcon when issuing a FalconDeploy command.

**To Reproduce**

```
~ $HostIds = (Import-Csv .\hostlist.csv).'Host ID'
~ Invoke-FalconDeploy -File FalconForensicsCollectorBrowser_1.0.277_eu1.exe -Timeout 300 -QueueOffline $True -HostIds $HostIds
~ Get-FalconQueue

[Write-Result] meta.powered_by=empower-api, meta.pagination.offset=0, meta.trace_id=faf499a5-a6cc-4af4-84b7-478d8b69cdfa, meta.pagination.total=0, meta.query_time=0.031280432, meta.pagination.limit=100
No queued Real-time Response sessions available.
At C:\Users\*USER*\Documents\WindowsPowerShell\Modules\PSFalcon\2.2.4\Public\psf-real-time-response.ps1:49 char:35
+ ... Sessions) { throw "No queued Real-time Response sessions available."  ...
    + CategoryInfo          : OperationStopped: (No queued Real-...ions available.:String) [], RuntimeException
    + FullyQualifiedErrorId : No queued Real-time Response sessions available.

```

**Expected behavior**
A list of hosts that are offline but in the Offline Queue.

**Environment (please complete the following information):**
 - OS: Microsoft Windows NT 10.0.22621.0
 - PowerShell: v5.1
 - PSFalcon: v2.2.4

**Additional context**
Trying to deploy ForensicFalcon out to estate. Many offline hosts offline and are not added to Offline Queue. User conducting the commands has RTR permissions. 
 
**Transcript content**
Attached below
 
1. Set $VerbosePreference = 'Continue'
2. Run Import-Module, Request-FalconToken, Start-Transcript, Show-FalconModule, the affected PSFalcon commands or script, and Stop-Transcript
3. Copy/paste transcript content
[PowerShell_transcript.txt](https://github.com/CrowdStrike/psfalcon/files/11088215/PowerShell_transcript.txt)

**Comment by bk-cs** [comment]
@59e5aaf4 thank you for the tip! It does seem that something changed in the RTR sessions API causing no values to return when using `commands_queued:1` rather than `commands_queued:true`. I have updated `Get-FalconQueue` for the next release to resovle this issue.

If you'd like to fix your local copy, you can modify the `Public\psf-real-time-response.ps1` file in your local module to change this line from...

```powershell
        Filter = "(deleted_at:null+commands_queued:1),(created_at:>'last $Days days'+commands_queued:1)"
```

To...
```powershell
        Filter = "(deleted_at:null+commands_queued:true),(created_at:>'last $Days days'+commands_queued:true)"
```

**Comment by PewlettHackard** [comment]
Hi all, can confirm this has given me visibility of the offline queue.

**Comment by bk-cs** [comment]
Leaving open for people to fix before release.

**Comment by bk-cs** [comment]
[2.2.5 release](https://github.com/CrowdStrike/psfalcon/releases/tag/2.2.5)
