### ISSUE TITLE
[ BUG ] `Edit-FalconDeviceControlPolicy` does not retain exception descriptions when adding additional exceptions

### ISSUE THREAD

**Issue by harrim4n** [CrowdStrike/psfalcon#306]
**Describe the bug**
When adding a new exception to a device policy which includes a description, the description of already existing exceptions is cleared.

**To Reproduce**
I used a script which basically does the same as the sample file: https://github.com/CrowdStrike/psfalcon/blob/7976423c1e67eadfc5b829862f64eed3194a854a/samples/policies/add-a-list-of-combined_id-exceptions-to-a-device-control-policy.ps1
In line 26, add the "description" parameter and set it to some string (multiline in my case, not sure if relevant).

**Expected behavior**
The existing exceptions should not be modified

**Environment (please complete the following information):**
 - OS: Debian 11
 - PowerShell: 7.3.3
 - PSFalcon: 2.2.4

**Additional context**
-
 
**Transcript content**
-

**Comment by bk-cs** [comment]
Thank you for the report! I was able to re-create this behavior. I suspect this is API related and not restricted to `Edit-FalconDeviceControlPolicy`. Here's why I think that:

* The script example you provided does not modify existing exceptions, it only adds new ones
* Modifying the script to add a description with the new exception still erases any existing descriptions

I'll investigate further and see if I can get an internal issue opened to get it fixed.

**Comment by bk-cs** [comment]
I have confirmed that this is an API issue and not restricted to PSFalcon. I've opened an internal ticket requesting a fix and I'll leave this issue open until I receive confirmation that it is resolved.

**Comment by bk-cs** [comment]
I confirmed that disappearing descriptions are no longer an issue on the API side.
