### ISSUE TITLE
PS Falcon (Get-FalconVulnerability) - Write-Result : [{"code":500,"message":"Internal Server Error:[ BUG ] <Add description>

### ISSUE THREAD

**Issue by kpoznanski5** [CrowdStrike/psfalcon#347]
Hello,

I am using PSFalcon 2.2.4 and 2.2.5 and started getting this error message when importing vulnerabilities using Get-FalconVulnerability.
The script runs into some exception. It successfully imports 597,599 rows out of 940,560 total and it errors out.
The PSFalcon 2.2.5 reports the following error:

Write-Result : [{"code":500,"message":"Internal Server Error: Please provide
trace-id=\u0027b429b6b6-cfec-4d32-9d24-ce6ad8d8f50d\u0027 to support"}]
At C:\PSFalcon\psfalcon-2.2.5\private\Private.ps1:627 char:17

            Write-Result $Object
            ~~~~~~~~~~~~~~~~~~~~
CategoryInfo : InvalidResult: (System.Threadin...esponseMessage
]:Task`1) [Write-Result], Exception
FullyQualifiedErrorId : b429b6b6-cfec-4d32-9d24-ce6ad8d8f50d,Write-Resul
t
I would greatly appreciate assistance in resolving this issue.
Thank you.

Kris

**Comment by bk-cs** [comment]
Given that this error doesn't provide any information beyond the `trace_id`, I recommend opening a ticket with CrowdStrike support.
