### ISSUE TITLE
When I use Invoke-FalconHostAction, should I use device ID unique to each host entries? If yes, I used the same but error stated No matching found for the ID. Please do assist

### ISSUE THREAD

**Issue by VintageArmour** [CrowdStrike/psfalcon#352]
**Description of your question**
A clear and concise description of what the question is.

**To Reproduce**
Steps to reproduce the behavior you are seeing.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Windows Server 2016, Windows 10]
 - PowerShell: [e.g. 5.1]
 - PSFalcon: [e.g. 2.1.4]

**Additional context**

**Comment by bk-cs** [comment]
Sorry, but I can't make sense of this question. Can you provide a log showing an error?

**Comment by bk-cs** [comment]
Closing due to lack of response.
