### ISSUE TITLE
[ BUG ] Unable to use severity `critical` with `Edit-FalconHorizonPolicy`

### ISSUE THREAD

**Issue by mdurnell** [CrowdStrike/psfalcon#363]
**Describe the bug**
`Edit-FalconHorizonPolicy` does not allow the value of `critical `for the `-Severity` parameter.

**To Reproduce**
Edit-FalconHorizonPolicy -Id 223 -Enabled $true -Severity critical

**Expected behavior**
Critical is a valid severity level for CSPM policies

**Environment (please complete the following information):**
 - OS: Windows 10
 - PowerShell: 5.1.19041.3570
 - PSFalcon: 2.2.5

**Comment by bk-cs** [comment]
Resolved in 2.2.6 release which has been published to GitHub and will be published on the PowerShell Gallery soon.
