### ISSUE TITLE
[ BUG ] User Management: List roles assigned to a user - Listed all roles in cid instead of user

### ISSUE THREAD

**Issue by dkang-firmus** [CrowdStrike/psfalcon#365]
**Describe the bug**
Get-FalconRole -UserId <id> should retrieve the roles that is assigned to the <id>. But what I get appears to be all roles available in the CID instead of the role assigned to the user.

**To Reproduce**
After authentication, run 'Get-FalconRole -UserId <id>'. Put in any uuid available in your environment.

**Expected behavior**
The output should describe specific roles that are granted to that particular user, instead of listing all available roles in the environment.

**Environment (please complete the following information):**
 - OS: Windows 10
 - PowerShell: 5.1
 - PSFalcon: 2.2.5

**Additional context**
none
 
**Transcript content**
none

**Comment by bk-cs** [comment]
Please see issue #313
