### ISSUE TITLE
`SendASync` error with `Invoke-FalconDeploy`

### ISSUE THREAD

**Issue by sjoshi17** [CrowdStrike/psfalcon#377]
![Error](https://github.com/CrowdStrike/psfalcon/assets/36763361/d9abf63e-fdbd-4c02-9d56-cfdf0b99ee60)

**Comment by sjoshi17** [comment]
I am executing command as below:
Invoke-FalconDeploy -HostId -Path *<path to FFC executable>* -Arguments "-cid <CID with
Checksum>" -QueueOffline $True

**Comment by bk-cs** [comment]
Did you properly import the module and request your token before attempting this?
```
Import-Module -Name PSFalcon
Request-FalconToken -ClientId ... -ClientSecret ... -Hostname ...
```
That error appears when the PSFalcon module is not properly loaded and the base API hostname is not set.

**Comment by sjoshi17** [comment]
To describe in detail as i am very new to the deployment of the same. 
I am using Ubuntu 20.04 on Virtual Box for testing purposes. The modules are successfully imported which i have also test using Get-Command.

![Modules imported](https://github.com/CrowdStrike/psfalcon/assets/36763361/0500c017-fab8-4518-9a79-bf23032c1f5d)


However, when i am running Get-FalconToken i am inserting the Client ID and Secret key which is throwing me an error as enclosed. 

![Error 2](https://github.com/CrowdStrike/psfalcon/assets/36763361/acf1a86d-8b7e-4ba5-9fcd-817685c4b9a8)

**Comment by bk-cs** [comment]
* Verify that you're not using IP allowlisting
* Try deleting and re-creating your client
* Verify that you're including your `Cloud` or `Hostname` in your `Request-FalconToken` syntax

**Comment by bk-cs** [comment]
Have you been able to verify the points above? Is this still an issue for you?
