### ISSUE TITLE
[ DOCUMENTATION ] `tags` should be included in the list of available filters for `Get-FalconHost`

### ISSUE THREAD

**Issue by ITsVeritas** [CrowdStrike/psfalcon#392]
**Describe the bug**
The documentation does not currently list `tags` as an available filter for the Get-FalconHost cmdlet but it does work with something like:
`Get-FalconHost -Filter "tags:'FalconGroupingTags/Test'"`

https://github.com/CrowdStrike/psfalcon/wiki/Get-FalconHost

**Comment by bk-cs** [comment]
Wiki page updated. Thank you!
