### ISSUE TITLE
[ QUESTION ] Client Secret as Secure String

### ISSUE THREAD

**Issue by swiru95** [CrowdStrike/psfalcon#395]
**Description of your question**
Should not Client Secret be treated as SecureString?

**To Reproduce**
REquest-FalconToken etc...

**Expected behavior**
Secure string is quite important credential - should be treated carefully, especially if it comes to EDR access.

**Environment (please complete the following information):**
n/a

**Additional context**
Security good practice and credential leakage prevention - logs, scripts etc.

**Comment by bk-cs** [comment]
Please see this discussion: https://github.com/CrowdStrike/psfalcon/discussions/101

I recommend using the Microsoft SecretStore module to protect your API client credentials: https://github.com/CrowdStrike/psfalcon/wiki/Authentication#securing-credentials
