### ISSUE TITLE
[ BUG ] `Index was out of range` error related to RTR sessions

### ISSUE THREAD

**Issue by mcj323s** [CrowdStrike/psfalcon#398]
**Describe the bug**
When authenticating and starting RTR sessions this issue randomly happens. I am not sure if this is an API issue or the powershell modules which worked last week. The problem happened 4/16 and now happens intermittently  since updating to .net 4.8.1

**To Reproduce**
Commands that I experienced the issue on.
Request-FalconToken
Session-Start
Invoke-FalconAdmin
Intermittenly 

**Environment (please complete the following information):**
 - OS: Windows 11 Enterprise 10.0.22631 Build 22631
 - PowerShell: 5.1- Running as user not admin. Modules are unfortunately in a network shared drive. Unable have been unable to figure out how to redirect powershell to a local drive do to the inabilty to adjust the profile.
 - PSFalcon: Reinstalled on 2.2.6 4/15/2024

**Additional context**
I am running a script that gathers a list of device ids,  creates a session token uses the Start-Session. Runs 6 commands waiting for each command to complete. Then it starts with a new device. Normally no issues. If this relates to the API performance I can report this do CrowdStrike.  
 
**Transcript content**
If possible, please include a PowerShell transcript.
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
At \My Documents\WindowsPowerShell\Modules\PSFalcon\2.2.6\public\real-time-response.ps1:1346 char:9
+       @(Invoke-Falcon @Param -Endpoint $Endpoint -UserInput $PSBoundP ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Invoke-Falcon], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException,Invoke-FalconSteps to reproduce the behavior.

**Expected behavior**
Normally a session key is created. Authentication token is created. 
Nothing is showing in the verbose output related to the API.

**Comment by bk-cs** [comment]
Can you try applying the fix detailed in this issue?

https://github.com/CrowdStrike/psfalcon/issues/382#issuecomment-1961927325
