### ISSUE TITLE
Error with Get-FalconQueue

### ISSUE THREAD

**Issue by Factorization** [CrowdStrike/psfalcon#5]
I get the following error when I run `Get-FalconQueue`. 

Error: A parameter cannot be found that matches parameter name 'SessionIds'.

![image](https://user-images.githubusercontent.com/10674846/105258261-329a3900-5b3e-11eb-8a70-3eac8432d8d3.png)

**Comment by bk-cs** [comment]
Another great catch, thanks! Fixed.
