### ISSUE TITLE
Edit-FalconScript - Please add -Content switch

### ISSUE THREAD

**Issue by datorr2** [CrowdStrike/psfalcon#51]
The API endpoint used by the `Edit-FalconScript` supports two methods of sending script updates: `content=` or `file=`

Unfortunately, it seems that the `file=` parameter doesn't work (or if it does, is highly unreliable).  However, `content=` is much more reliable.

It would be nice if the `Edit-FalconScript` command would support using a `-Content` parameter in lieu of the `-Path`  parameter.

Side note: I have created a case in support portal regarding the bug with the API.

**Comment by bk-cs** [comment]
Do you have any examples where the `file` parameter isn't working? I didn't run into any in my testing, which is why I chose `file` over `content`.

If there's a problem with the specific parameter (and it's related to how PSFalcon works, rather than the API) I'm happy to get that fixed...but I'm admittedly a little hesitant to add `content` if it would end up producing more confusion than solving problems. :)

**Comment by datorr2** [comment]
I've actually been testing and troubleshooting for quite some time, and found `Edit-FalconScript` to be wildly inconsistent.  That's what lead me to investigate the API endpoints outside of PSFalcon module.

What happens with the API calls is, regardless of which is used, the data returned says that the single targeted ID was updated (resources_affected: 1).  Upon looking at the script in the Falcon console, it shows all values updated except the actual script contents.

The following API calls were performed with `curl` using what was generated from the swagger-eagle API page:

```
The following API call does not work and will not update the script in the cloud:
==================================================================
PATCH /real-time-response/entities/scripts/v1 HTTP/1.1
Host: <api>
User-Agent: curl/7.73.0
accept: application/json
authorization: Bearer eyJhbGciOiJSUzI...
Content-Length: 698
Content-Type: multipart/form-data; boundary=------------------------0a71c906c829876d

--------------------------0a71c906c829876d
Content-Disposition: form-data; name="id"

<falcon_script_id>
--------------------------0a71c906c829876d
Content-Disposition: form-data; name="file"; filename="randomFile"
Content-Type: application/octet-stream

Write-Output "Hello World"

--------------------------0a71c906c829876d
Content-Disposition: form-data; name="name"

api-test
--------------------------0a71c906c829876d
Content-Disposition: form-data; name="comments_for_audit_log"

api testing
--------------------------0a71c906c829876d
Content-Disposition: form-data; name="permission_type"

group
--------------------------0a71c906c829876d--
==================================================================
```
```
The following API call does work correctly and updates the script in the cloud:
==================================================================
PATCH /real-time-response/entities/scripts/v1 HTTP/1.1
Host: <api>
User-Agent: curl/7.73.0
accept: application/json
authorization: Bearer eyJhbGciOiJSUzI1...
Content-Length: 644
Content-Type: multipart/form-data; boundary=------------------------2aa938198a75acba

--------------------------2aa938198a75acba
Content-Disposition: form-data; name="id"

<falcon_script_id>
--------------------------2aa938198a75acba
Content-Disposition: form-data; name="name"

api-test
--------------------------2aa938198a75acba
Content-Disposition: form-data; name="comments_for_audit_log"

api testing
--------------------------2aa938198a75acba
Content-Disposition: form-data; name="permission_type"

group
--------------------------2aa938198a75acba
Content-Disposition: form-data; name="content"

this is a test
--------------------------2aa938198a75acba--
==================================================================
```

**Comment by datorr2** [comment]
> If there's a problem with the specific parameter (and it's related to how PSFalcon works, rather than the API) I'm happy to get that fixed...

The bug, I believe, is ultimately with the API; however, I made the suggestion about providing an alternative functionality for the cmdlet because it means that until the API is fixed, `Edit-FalconScript` is not usable for us.

**Comment by bk-cs** [comment]
Thank you for that thorough response! I'll do some testing and see if I can add a secondary option (or maybe switch from `file` to `content` if that doesn't seem like it will work) in the next update.
