### ISSUE TITLE
List of cloud service types in /settings/entities/policy/v1:get is not current

### ISSUE THREAD

**Issue by awesomecogs** [CrowdStrike/psfalcon#54]
The list of cloud service types [here](https://github.com/CrowdStrike/psfalcon/blob/master/Data/Endpoints/settings.psd1#L32) in /settings/entities/policy/v1:get is not comprehensive.

It currently lists:
`enum = @("EC2","IAM","KMS","ACM","ELB","NLB/ALB","EBS","RDS","S3","Redshift",                        "NetworkSecurityGroup","VirtualNetwork","Disk","PostgreSQL","AppService","KeyVault",                        "VirtualMachine","Monitor","StorageAccount","LoadBalancer","SQLServer")`

But I think it should include:
* Both services
  * `Any`
* AWS
  * `CloudFormation, Cloudfront, CloudTrail, CloudWatch Logs, Config, DynamoDB, ECR, EFS, EKS, Elasticache, EMR, GuardDuty, Kinesis, Lambda, Serverless Application Repository, SES, SNS, SQS, SSM`
* Azure
  * `ACR, Identity, Kubernetes, SQL Database, SQLDatabase, Subscriptions`

This issue exists in CS's swagger [here](https://assets.falcon.crowdstrike.com/support/api/swagger.html#/cspm-registration/GetCSPMPolicySettings), and I have a feeling the psfalcon list was pulled from there.  I've opened CS case 00530792 for the swagger issue, and completely understand if you want to wait for them to update their "official" swagger before updating psfalcon.

**Comment by bk-cs** [comment]
Thank you for the report! You're correct, PSFalcon pulls its data from Swagger. I think this might be an issue that's not limited to PSFalcon and could include what services Horizon supports, what the API accepts, etc. I'll keep an eye on the ticket and add additional services once I find out more.

**Comment by awesomecogs** [comment]
CS updated `/settings/entities/policy/v1:get` with all service types and case 00530792 has been closed.

As of today, swagger is showing the following:
`enum = @("ACM","ACR","AppService","CloudFormation","CloudTrail","CloudWatch Logs","Cloudfront","Config","Disk","DynamoDB","EBS","EC2","ECR","EFS","EKS","ELB","EMR","Elasticache","GuardDuty","IAM","Identity","KMS","KeyVault","Kinesis","Kubernetes","Lambda","LoadBalancer","Monitor","NLB/ALB","NetworkSecurityGroup","PostgreSQL","RDS","Redshift","S3","SES","SNS","SQLDatabase","SQLServer","SQS","SSM","Serverless Application Repository","StorageAccount","Subscriptions","VirtualMachine","VirtualNetwork")`

**Comment by awesomecogs** [comment]
I've created https://github.com/awesomecogs/psfalcon/tree/patch-1 with the new values per swagger.  I'll let you merge/commit/whatever if you wish.

**Comment by bk-cs** [comment]
Thank you! I'm in the middle of doing a re-write of most of the commands, so I'll ensure these new values are included in the [next update](https://github.com/CrowdStrike/psfalcon/tree/2.1.0).

**Comment by bk-cs** [comment]
Completed in [v2.1.0-alpha](https://github.com/CrowdStrike/psfalcon/releases/tag/v2.1.0-alpha).
