### ISSUE TITLE
Errors catching

### ISSUE THREAD

**Issue by mark260486** [CrowdStrike/psfalcon#61]
Hi, guys!

Could you advice a way to catch such errors to log them as a result of request?
PS code i tried screenshot: https://imgur.com/PXjhTnG
Thank you!

**Comment by bk-cs** [comment]
I'm not sure what you mean by this request. The errors are output using `Write-Error` and are accessible through the automatic `$Error` variable. 

If you're writing a script, you should be able to try/catch and output the errors in a specific way.

**Comment by mark260486** [comment]
Hi, @bk-cs! Thanks for reply! I didn't know about $Error variable, standart try-catch tutorials are not cover it. Thanks a lot, it works perfect.
