### ISSUE TITLE
Ad custom user agent string for tracking purpoes

### ISSUE THREAD

**Issue by ckachigian** [CrowdStrike/psfalcon#62]
Use a pattern for the user agent string for PS Falcon so we can better track usage / adoption across the customer base.

Example: vendor-integration_name/version
Example: crowdstrike-falconpy/0.5.2

**Comment by bk-cs** [comment]
Added to [2.1.0](https://github.com/CrowdStrike/psfalcon/tree/2.1.0) to be included with that release.

**Comment by bk-cs** [comment]
Completed in [v2.1.0-alpha](https://github.com/CrowdStrike/psfalcon/releases/tag/v2.1.0-alpha).
