### ISSUE TITLE
Varying Property Count when using get-falconhost

### ISSUE THREAD

**Issue by gmellendorf-dxc** [CrowdStrike/psfalcon#66]
Using psfalcon 2.0.8.

Some hosts in my environment don't have values for some of their properties.  It appears that the returned object is defined based on the first host returned.  Here are successive run of get-falconhost:

PS C:\> (get-falconhost -Detailed -All -Limit 5000 | gm | where-object{$_.MemberType -eq "NoteProperty"}).count 
45 

PS C:\> (get-falconhost -Detailed -All -Limit 5000 | gm | where-object{$_.MemberType -eq "NoteProperty"}).count 
39 

PS C:\> (get-falconhost -Detailed -All -Limit 5000 | gm | where-object{$_.MemberType -eq "NoteProperty"}).count 
39 

PS C:\> (get-falconhost -Detailed -All -Limit 5000 | gm | where-object{$_.MemberType -eq "NoteProperty"}).count 
45 

Property Comparison - Properties Missing Limited Results
------------------------------------------------------------------------------------ 
PS C:\> $g1 = get-falconhost -Detailed -All -Limit 5000 | gm | where-object{$_.MemberType -eq "NoteProperty"} 
PS C:\> $g1.count 39 
PS C:\> $g2 = get-falconhost -Detailed -All -Limit 5000 | gm | where-object{$_.MemberType -eq "NoteProperty"} 
PS C:\> $g2.count 45 

PS C:\> Compare-Object -ReferenceObject $g1.name -DifferenceObject $g2.name 

InputObject SideIndicator 
----------- ------------- 
local_ip => 
machine_domain => 
mac_address => 
ou => 
provision_status => 
site_name => 

Need help to get consistent results...

**Comment by bk-cs** [comment]
This is not something that PSFalcon is doing, this is the API. If the device does not have the property, the field will be null (and in some cases, the property is not present at all). In my testing environment, none of my devices are joined to a domain, and the `machine_domain`,  `ou` and `site_name` properties do not show up in a `Get-FalconHost` result.
