### ISSUE TITLE
Ambiguous Error when running commands with invalid token

### ISSUE THREAD

**Issue by datorr2** [CrowdStrike/psfalcon#84]
I goofed and didn't specify the correct cloud when trying to generate my token, and so I had a token that was invalid.  This allowed me to run commands without asking for a ClientId and ClientSecret again, but it kept throwing this error:

```powershell
Write-Error: C:\Program Files\WindowsPowerShell\Modules\PSFalcon\Public\detects.ps1:92
Line |
  92 |          Invoke-Falcon @Param
     |          ~~~~~~~~~~~~~~~~~~~~
     | [Write-Result] Unexpected 'ContentType'.
```

Didn't know if you would want to work in an error about having an invalid token:

```powershell
( (Test-FalconToken).Token -eq $false )
```

**Comment by bk-cs** [comment]
That's a new one...

I can tell from your error that the module is not in the proper location. PowerShell gets angry when you have modules running from the wrong directories. Can you try following the [Installation guide](https://github.com/CrowdStrike/psfalcon/wiki/Installation)? Installing through the PowerShell Gallery provides the most consistent results. If you have to do the manual installation, verify that the module is installed with the proper path structure and let me know if the errors continue.

**Comment by datorr2** [comment]
I deleted my manual install of PSFalcon v2.1.4 and instead installed via PowerShell Gallery (v2.1.3)

```powershell
[Core@7.1.4:~]$ Import-Module PSFalcon
[Core@7.1.4:~]$ Get-Module PSFalcon

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.1.3                 PSFalcon                            {Add-FalconCidGroupMember, Add-FalconGroupRole, Add-FalconHostTag, Add-FalconRo…

[Core@7.1.4:~]$ Test-FalconToken
[Core@7.1.4:~]$ Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
Write-Error: C:\Program Files\WindowsPowerShell\Modules\PSFalcon\2.1.3\Public\detects.ps1:92
Line |
  92 |          Invoke-Falcon @Param
     |          ~~~~~~~~~~~~~~~~~~~~
     | [Write-Result] Unexpected 'ContentType'.

[Core@7.1.4:~]$ Test-FalconToken

Token Hostname                    ClientId                         MemberCid
----- --------                    --------                         ---------
False https://api.crowdstrike.com REDACTED

[Core@7.1.4:~]$
```

**Comment by bk-cs** [comment]
* What cloud is your API Client associated with?

US-1, US-2 and EU-1 all have redirection enabled, and should redirect automatically if you attempt a token request in US-1 (which is what happens when you run a command without requesting a token).

* Even after reinstalling, you're using Core, yet the module is in the Desktop path. How did you install it to have it end up like that?

When using PowerShell Core and installing for all users, the module folder used is `C:\Program Files\PowerShell\Modules\PSFalcon\<version>`.

If using PowerShell Desktop and installing for all users, it's `C:\Program Files\WindowsPowerShell\Modules\PSFalcon\<version>`.

I tried to replicate the behavior you're seeing by moving my module folder from my typical `CurrentUser` module path (the recommended folder for installation within the guide; `$Home\Documents\WindowsPowerShell\Modules\PSFalcon`) to `Program Files`, but my credential set for US-2 properly redirected me to US-2.

Can you run these two steps (from PowerShell Core) and try again?

```
Uninstall-Module PSFalcon -AllVersions
Install-Module PSFalcon -Scope CurrentUser
```

The specific error you're receiving is only returned when a response is received and that response doesn't contain a `ResponseHeaders.ContentType` of `text/html` or `application/json`. Something still seems to be loading improperly.

**Comment by bk-cs** [comment]
Here's what happens when I try it with credentials for US-2. It fails on the initial attempt (maybe because the hostname redirection didn't get picked up?) and then works as expected. Still not a great error, but not the one you're getting:
```
PS> Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
Write-Error: C:\Program Files\WindowsPowerShell\Modules\psfalcon\2.1.3\Public\detects.ps1:92
Line |
  92 |          Invoke-Falcon @Param
     |          ~~~~~~~~~~~~~~~~~~~~
     | Exception calling "SendAsync" with "1" argument(s): "An invalid request URI was provided. The request
     | URI must either be an absolute URI or BaseAddress must be set."

PS> Get-FalconDetection
<detection_id>
<detection_id>
```

**Comment by datorr2** [comment]
@bk-cs my cloud is US-GOV-1  :P

I install all of my PowerShell modules using Desktop 5.1 to ensure it gets loaded regardless of the edition I use.  It helps when developing scripts that are cross-compatible.

**Comment by bk-cs** [comment]
I'm still only getting the "SendAsync" error when I try it with my US-GOV-1 credentials:

```
PS> Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
Write-Result: C:\Program Files\WindowsPowerShell\Modules\psfalcon\2.1.3\Public\oauth2.ps1:124
Line |
 124 |                  $Result = Write-Result $Response
     |                            ~~~~~~~~~~~~~~~~~~~~~~
     | 400: Failed to generate access token for clientID=REDACTED.

Write-Error: C:\Program Files\WindowsPowerShell\Modules\psfalcon\2.1.3\Public\detects.ps1:92
Line |
  92 |          Invoke-Falcon @Param
     |          ~~~~~~~~~~~~~~~~~~~~
     | Exception calling "SendAsync" with "1" argument(s): "An invalid request URI was provided. The request
     | URI must either be an absolute URI or BaseAddress must be set."

PS> Get-FalconDetection
ClientId:
```
I'm updating to PowerShell v7.1.4 to try that.

**Comment by bk-cs** [comment]
Ok, I added a break if the authorization token is missing. Please try replacing your `Private\Private.ps1` file with the latest from the repo, or re-install your module from source.

In my case, it ends up looking like this:
```
PS> Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
Write-Result: C:\Program Files\WindowsPowerShell\Modules\psfalcon\2.1.4\Public\oauth2.ps1:124
Line |
 124 |                  $Result = Write-Result $Response
     |                            ~~~~~~~~~~~~~~~~~~~~~~
     | 400: Failed to generate access token for clientID=REDACTED.
```
It might end up showing no output for you since it wasn't showing the right error in the first place, but I'm interested to see what it will do.

**Comment by datorr2** [comment]
@bk-cs So, I currently have `PSFalcon` `v2.1.3`, but with `Private\Private.ps1` and `Public\psfalcon.ps1` replaced with the latest, and I am still getting the same `[ContentType]` error, both in Core 7.1.4 and Desktop 5.1.18362.1714

**Comment by bk-cs** [comment]
Logically, based on what the script is doing, I can't understand how you're ending up with that error. There should be no response content for it to evaluate to determine that you're not getting a Json or HTML response and it should return nothing.

What happens if you delete the following lines from `Private\Private.ps1` under the `Write-Result` function?

```
            } else {
                # Error if not 'application/json' or 'text/html'
                $Request
                throw "[Write-Result] Unexpected 'ContentType'."
```

I'll assume it at least takes that error away, but you should still be receiving an error because you can't request a token before the `ContentType` error was produced.

**Comment by datorr2** [comment]
Fascinating.  It fails more gracefully.

```powershell
Set-Location (Split-Path (Get-Module PSFalcon -ListAvailable).Path)
# ----
vim .\Private\Private.ps1
# ----
(Get-Content .\Private\Private.ps1)[713..718]
             }<# else {
                # Error if not 'application/json' or 'text/html'
                $Request
                throw "[Write-Result] Unexpected 'ContentType'."
            }
            #>
# ----
Import-Module PSFalcon
# ----
Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
# ----
Test-FalconToken

Token Hostname                    ClientId MemberCid
----- --------                    -------- ---------
False https://api.crowdstrike.com
```

I did some tinkering and $Result is indeed an object:
<details>
<summary>Click to expand.</summary>

```json
{
    "Result": {
        "Version": {
            "Major": 1,
            "Minor": 1,
            "Build": -1,
            "Revision": -1,
            "MajorRevision": -1,
            "MinorRevision": -1
        },
        "Content": {
            "Headers": [
                {
                    "Key": "Content-Length",
                    "Value": [
                        "0"
                    ]
                }
            ]
        },
        "StatusCode": 403,
        "ReasonPhrase": "Forbidden",
        "Headers": [
            {
                "Key": "X-Cs-Traceid",
                "Value": [
                    "8372225a-fade-45bd-bfe0-77cc027e5e4b"
                ]
            },
            {
                "Key": "X-Ratelimit-Limit",
                "Value": [
                    "300"
                ]
            },
            {
                "Key": "X-Ratelimit-Remaining",
                "Value": [
                    "298"
                ]
            },
            {
                "Key": "Date",
                "Value": [
                    "Fri, 17 Sep 2021 22:39:18 GMT"
                ]
            }
        ],
        "RequestMessage": {
            "Version": {
                "Major": 1,
                "Minor": 1,
                "Build": -1,
                "Revision": -1,
                "MajorRevision": -1,
                "MinorRevision": -1
            },
            "Content": {
                "Headers": [
                    {
                        "Key": "Content-Type",
                        "Value": [
                            "application/x-www-form-urlencoded; charset=utf-8"
                        ]
                    },
                    {
                        "Key": "Content-Length",
                        "Value": [
                            "97"
                        ]
                    }
                ]
            },
            "Method": {
                "Method": "POST"
            },
            "RequestUri": "https://api.crowdstrike.com/oauth2/token",
            "Headers": [
                {
                    "Key": "ContentType",
                    "Value": [
                        "application/x-www-form-urlencoded"
                    ]
                },
                {
                    "Key": "Accept",
                    "Value": [
                        "application/json"
                    ]
                },
                {
                    "Key": "User-Agent",
                    "Value": [
                        "crowdstrike-psfalcon/2.1.3"
                    ]
                }
            ],
            "Properties": {}
        },
        "IsSuccessStatusCode": false
    },
    "Id": 686,
    "Exception": null,
    "Status": 5,
    "IsCanceled": false,
    "IsCompleted": true,
    "CreationOptions": 0,
    "AsyncState": null,
    "IsFaulted": false,
    "AsyncWaitHandle": {
        "Handle": 2412,
        "SafeWaitHandle": {
            "IsInvalid": false,
            "IsClosed": false
        }
    },
    "CompletedSynchronously": false
}
```
</details>

**Comment by bk-cs** [comment]
Ok, so there's no `Result.Content` for it to evaluate (only `Headers`), which means it should be returning `$null` if the `ContentType` error is removed from `Private\Private.ps1`. 

It still doesn't explain why I can't recreate this using US-GOV-1 credentials and the same steps. Are you running PowerShell Core  from within Windows, or WSL?

**Comment by datorr2** [comment]
I use PowerShell on Windows, no WSL installed.  I just customize my prompt in my `profile.ps1`

<details>
<summary>Click to expand.</summary>

```powershell

# Set Prompt
function Prompt {
    $Edition = $PSVersionTable.PSEdition
    if ($Edition -match 'Desktop') {
        $Version = @($PSVersionTable.PSVersion.Major,$PSVersionTable.PSVersion.Minor) -join "."
    } else {
        $Version = $PSVersionTable.PSVersion.ToString()
    }
    $CurrLoc = $ExecutionContext.SessionState.Path.CurrentLocation
    $UsersPath = 'C:\Users\' -replace '\\','\\'
    $UserHome = $env:USERPROFILE -replace '\\','\\'
    $IsAdmin = if (Test-IsAdmin) {'#'} else {'$'}
    $ParsedPath = ($CurrLoc -replace $UserHome,'~') -replace $UsersPath,'~'
    "[$($Edition)@$($Version):$($ParsedPath)]$($IsAdmin)$('>' * ($nestedPromptLevel)) ";
    # .Link
    # https://go.microsoft.com/fwlink/?LinkID=225750
    # .ExternalHelp System.Management.Automation.dll-help.xml
}
```
</details>

I run on Windows 10 (1909) Build 18363.1734, with whatever stock PowerShell Desktop comes with (5.1.18362.1714) with PowerShell Core 7.1.4 installed using MSI installer.
My PowerShell Core shortcut uses:
```
"C:\Program Files\PowerShell\7\pwsh.exe" -WorkingDirectory ~
```
PowerShell Desktop shortcut uses:
```
%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe
```

**Comment by bk-cs** [comment]
Hmm, ok. So now there's no more ambiguous error, but you're also not getting a failed auth request?

When using PSFalcon v2.1.4 from source in PowerShell Core v7.1.4, I get this:
```
PS> Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
Write-Result: C:\git\crowdstrike\psfalcon\Public\oauth2.ps1:124
Line |
 124 |                  $Result = Write-Result $Response
     |                            ~~~~~~~~~~~~~~~~~~~~~~
     | 400: Failed to generate access token for clientID=REDACTED.
```

When using PSFalcon v2.1.3 from the PowerShell Gallery, installed within PowerShell Desktop v5.1, but imported into PowerShell Core v7.1.4, I get this:
```
PS C:\Users\brend> Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
Write-Result: C:\Program Files\WindowsPowerShell\Modules\psfalcon\2.1.3\Public\oauth2.ps1:124
Line |
 124 |                  $Result = Write-Result $Response
     |                            ~~~~~~~~~~~~~~~~~~~~~~
     | 400: Failed to generate access token for clientID=REDACTED.

Write-Error: C:\Program Files\WindowsPowerShell\Modules\psfalcon\2.1.3\Public\detects.ps1:92
Line |
  92 |          Invoke-Falcon @Param
     |          ~~~~~~~~~~~~~~~~~~~~
     | Exception calling "SendAsync" with "1" argument(s): "An invalid request URI was provided. The request
     | URI must either be an absolute URI or BaseAddress must be set."
```

Both times I get the `Failed to generate access token for clientID` message, which you seem to never get. Can you try re-running the commands with `$VerbosePreference = 'Continue'` to see if something else useful shows up?

Unless we can narrow down why you're not getting that error message, I can't really figure out what to change to make it any better. So far you're the only person that has reported the error message like this and I can't make it happen.

**Comment by datorr2** [comment]
```powershell
$VerbosePreference = 'Continue'
Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
```
```
VERBOSE: [ApiClient.Invoke] POST https://api.crowdstrike.com/oauth2/token
VERBOSE: [ApiClient.Invoke] ContentType: application/x-www-form-urlencoded, Accept: application/json
VERBOSE: [ApiClient.Invoke] 403: Forbidden
Invoke-Falcon : [Write-Result] Unexpected 'ContentType'.
At C:\Program Files\WindowsPowerShell\Modules\PSFalcon\2.1.3\Public\detects.ps1:92 char:9
+         Invoke-Falcon @Param
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Falcon
```

**Comment by bk-cs** [comment]
Did you revert back to v2.1.3 or undo the removal of the `ContentType` error? That shouldn't be produced anymore.

What happens if you run these commands in PowerShell Desktop (v5.1; where the module is installed)?

**Comment by datorr2** [comment]
With PowerShell Desktop v5.1:

```powershell
Uninstall-Module PSFalcon
Install-Module PSFalcon

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the
Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y

Import-Module PSFalcon
Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
Invoke-Falcon : [Write-Result] Unexpected 'ContentType'.
At C:\Program Files\WindowsPowerShell\Modules\PSFalcon\2.1.3\Public\detects.ps1:92 char:9
+         Invoke-Falcon @Param
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Falcon
```

**Comment by bk-cs** [comment]
Sorry, I meant to run the modified PSFalcon module that we had used to remove the `ContentType` error.

Either way, you're still not getting the `400: Failed to generate access token for clientID` error that's normally displayed by the API, and I can't explain why. My assumption is that it's something unique with your setup, since I also used v7.1.4, with the module installed under PowerShell v5.1 for "AllUsers" and I get the error when you don't.

Let me see if I can force an error to be generated when there's no token present.

**Comment by bk-cs** [comment]
Ok, try replacing `Public\oauth2.ps1` in your local module directory with the [most recent commit](https://raw.githubusercontent.com/CrowdStrike/psfalcon/286456c4001cb893768177b8ec97a0217f801e35/Public/oauth2.ps1). I added an `Authorization token request failed` message, which I expect you'll see in this scenario. 

In my environment, it looks like this:
```
PS> Request-FalconToken
ClientId: REDACTED
ClientSecret: REDACTED
Write-Result: C:\git\crowdstrike\psfalcon\Public\oauth2.ps1:124
Line |
 124 |                  $Result = Write-Result $Response
     |                            ~~~~~~~~~~~~~~~~~~~~~~
     | 400: Failed to generate access token for clientID=REDACTED.

Exception: C:\git\crowdstrike\psfalcon\Public\oauth2.ps1:140
Line |
 140 |                      throw 'Authorization token request failed.'
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Authorization token request failed.

PS>
```

**Comment by datorr2** [comment]
At this point, I don't even know any more.  XD

```powershell
Uninstall-Module PSFalcon
Install-Module PSFalcon

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y

Set-Location (Split-Path (Get-Module PSFalcon -ListAvailable).Path)
Set-Location .\Public

Rename-Item .\oauth2.ps1 .\oauth2.ps1.orig
Invoke-RestMethod -Uri https://raw.githubusercontent.com/CrowdStrike/psfalcon/286456c4001cb893768177b8ec97a0217f801e35/Public/oauth2.ps1

Import-Module PSFalcon

Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
Invoke-Falcon : [Write-Result] Unexpected 'ContentType'.
At C:\Program Files\WindowsPowerShell\Modules\PSFalcon\2.1.3\Public\detects.ps1:92 char:9
+         Invoke-Falcon @Param
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Falcon
```
Still the same error with Desktop 5.1 and Core 7.1.4.

**Comment by bk-cs** [comment]
Can you be sure there are no other versions of PSFalcon that are loading? If you add the `-AllVersions` parameter it should delete everything--though I don't know if the Core-from-Desktop module import process will get in the way.
```
Uninstall-Module PSFalcon -AllVersions
```
The `ContentType` error will continue to be there as long as you keep using v2.1.3. v2.1.4 has that error removed. If everything is loading properly with the new `oauth2.ps` file, I would expect you to see the same output I saw (maybe excluding the initial `400: Failed to generate access token for clientID` error).

**Comment by datorr2** [comment]
Okay, so I downloaded all of the current code as a ZIP file and placed it into the v2.1.4 directory.

```powershell
Get-ExecutionPolicy
Bypass

Import-Module PSFalcon -RequiredVersion 2.1.4

Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
Invoke-Falcon : Unable to find type [ApiClient].
At C:\Program Files\WindowsPowerShell\Modules\PSFalcon\2.1.4\Public\detects.ps1:92 char:9
+         Invoke-Falcon @Param
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Falcon
```

**Comment by bk-cs** [comment]
`Import-Module PSFalcon -RequiredVersion 2.1.4` is not the proper way to import a local module. It will search your module folders before importing the local files.

You can `Import-Module .\PSFalcon.psd1` if you're in the current directory, or `Import-Module .\path\to\psfalcon\folder`.

**Comment by datorr2** [comment]
So, I have been completely removing all versions of PSFalcon for this testing, but every time I reinstall, I either use `Install-Module` and get `v2.1.3` or manually download into the same module directory (`C:\Program Files\WindowsPowerShell\Modules`).

So I tried to clone the repo at 286456c into temp and do a local load (please excuse my custom prompt):

```powershell
┌─(Desktop@5.1)-[~\AppData\Local\Temp]
└─# foreach ($dir in ($env:PSModulePath -split ';')) { Get-ChildItem -Path "$dir\PSFalcon" -Recurse }
# No files found
┌─(Desktop@5.1)-[~\AppData\Local\Temp]
└─# cd $env:Temp
┌─(Desktop@5.1)-[~\AppData\Local\Temp]
└─# git clone https://github.com/CrowdStrike/psfalcon.git PSFalcon
Cloning into 'PSFalcon'...
remote: Enumerating objects: 1334, done.
remote: Counting objects: 100% (1200/1200), done.
remote: Compressing objects: 100% (698/698), done.
Receiving objects: 100% (1334/1334), 818.36 KiB | 863.00 KiB/s, done.
Resolving deltas: 100% (964/964), done.
┌─(Desktop@5.1)-[~\AppData\Local\Temp]
└─# Import-Module .\PSFalcon\PSFalcon.psd1
┌─(Desktop@5.1)-[~\AppData\Local\Temp]
└─# (Get-Command -Module PSFalcon)[0]

CommandType     NameVersion    Source
-----------     -----------    ------
Function        Add-FalconCidGroupMember2.1.4      PSFalcon


┌─(Desktop@5.1)-[~\AppData\Local\Temp]
└─# Get-FalconDetection
ClientId: REDACTED
ClientSecret: REDACTED
Invoke-Falcon : Authorization token request failed.
At C:\Users\damian.torres\AppData\Local\Temp\PSFalcon\Public\detects.ps1:92 char:9
+         Invoke-Falcon @Param
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Falcon
```

**Comment by bk-cs** [comment]
Perfect--that's exactly what we're expecting to see. I still can't explain why you're not getting the `400` error from the API, but at least you have the token request failure. Does that satisfy the initial request? Or would you rather see the error saying something different?

**Comment by datorr2** [comment]
Oh, no, that's fine.  Like I said, due to the original error I was receiving, I couldn't tell why my token wasn't working.  Seeing this error would definitely clue me (and others) in so there'll be less head-scratching.  :D

Thank you!

**Comment by bk-cs** [comment]
Thanks for all your help troubleshooting! This additional error has been added to the v2.1.4 release.
